version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=yourpassword
      - DB_NAME=client_management
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - mynetwork
    restart: always

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: client_management
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
